services:
  app-assembly-web:
    depends_on:
    - env-kafka
    - env-postgres
    - env-keycloak
    - env-minio
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      APP_MINIO_BUCKETS_0_NAME: app-public-document
      APP_MINIO_BUCKETS_1_NAME: app-public-image
      APP_MINIO_BUCKETS_1_UPLOAD_POLICY_CONTENT_LENGTH: 10M
      APP_MINIO_BUCKETS_1_UPLOAD_POLICY_CONTENT_TYPE: image/
      APP_MINIO_BUCKETS_2_NAME: app-product-image
      APP_MINIO_BUCKETS_2_UPLOAD_POLICY_CONTENT_LENGTH: 10M
      APP_MINIO_BUCKETS_2_UPLOAD_POLICY_CONTENT_TYPE: image/
      APP_MINIO_CLIENT_ACCESS_KEY: y5LeRZ84J4SsenpaIxMl
      APP_MINIO_CLIENT_SECRET_KEY: AZitoDkffcEYFYUmV4CGv1jr2fiXWIw4uSvdFlDu
      APP_MINIO_CLIENT_TARGET_SERVER: http://env-minio:9000
      JAVA_OPTS: -Xmx512m -Xms256m
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_DATASOURCE_URL: jdbc:postgresql://env-postgres:5432/app
      SPRING_DATASOURCE_USERNAME: app
      SPRING_KAFKA_BOOTSTRAP_SERVERS: env-kafka:29092
    image: store/assembly_web:1.0.0-SNAPSHOT
    links:
    - env-haproxy:auth.local.example.com
    profiles:
    - app
    restart: unless-stopped
